apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
  labels: {
    app: nginx ,
    environment: pord
  }
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: nginx
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.baifendian.com/lifeng.zhang/nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: myregistrykey
